server:
  port: 8081
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
    date-format: java.text.SimpleDateFormat
  profiles:
    active: development
  main:
    banner-mode: "off"
---
spring:
  profiles: development
server:
  address: localhost
---
spring:
  profiles: production
server:
  address: localhost